apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: k8s-wp
  labels:
    app: k8s-wp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-wp
  template:
    metadata:
      labels:
        app: k8s-wp
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          volumeMounts:
          - name: wordpress-persistent-storage
            mountPath: /var/www/html
          - name: wp-config
            mountPath: /etc/nginx/conf.d/default.conf
            subPath: default.conf
          ports:
            - containerPort: 80
              name: wp-web-svc
              protocol: TCP

        - name: wordpress
          image: nghiach/wordpress-fpm
          volumeMounts:
            - name: wordpress-persistent-storage
              mountPath: /var/www/html
            # test php 
            # - name: wp-config
            #   mountPath: /var/www/html/index.php
            #   subPath: index.php
          env:
          - name: WORDPRESS_WP_HOST
            value: your-site.com
          - name: WORDPRESS_WP_HOME
            value: http://your-site.com
          - name: WORDPRESS_WP_SITEURL
            value: http://your-site.com
          - name: WORDPRESS_DB_HOST
            value: mysql:3306
          - name: WORDPRESS_DB_USER
            value: root
          - name: WORDPRESS_DB_NAME
            value: wordpress
          - name: WORDPRESS_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql
                key: password
        # replace with your own docker
        - image: nghiach/wordpress-img
          name: wordpress-image
          volumeMounts:
            - name: wordpress-persistent-storage
              mountPath: /var/www/html
          command: ["/bin/sh"]
          args: ["-c", "cp -r /usr/src/html /var/www/; while true; do echo hello; sleep 3600;done"]
      volumes:
        - name: wordpress-persistent-storage
          gcePersistentDisk:
            pdName: k8s-wp-disk
            fsType: ext4
        - name: wp-config
          configMap:
            name: wp-config